# Generated by Django 4.0 on 2022-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0011_alter_gallery_first_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
