# Generated by Django 4.0 on 2022-07-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcardApp', '0012_ordermodel_is_complete_ordermodel_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='finish',
            field=models.CharField(choices=[('matte', 'Matte'), ('gloss', 'Gloss'), ('non lamination', 'Non Lamination')], default='matt', max_length=20),
        ),
    ]
