# Generated by Django 4.0 on 2022-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_pin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
